name: Mirror to Codeberg

on:
  push:
    branches:
      - main
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        run: |
          git remote add codeberg https://${{ secrets.CODEBERG_TOKEN }}@codeberg.org/wts/faroleiro.git
          git push --mirror codeberg